export { HeritageTemplate } from './HeritageTemplate'
export { ClarityTemplate } from './ClarityTemplate'
export { ImpactTemplate } from './ImpactTemplate'
export { PrecisionTemplate } from './PrecisionTemplate'
export { ExecutiveEdgeTemplate } from './ExecutiveEdgeTemplate'
